### ISSUE TITLE
I believe this should cause an issue since "encodedBytes" is not defined 

### ISSUE THREAD

**Issue by amersulieman** [Moesif/moesif-aws-lambda-python#7]
https://github.com/Moesif/moesif-aws-lambda-python/blob/323765c1e6e2c9ea49bb41d1f9ba15ddd1f3aa06/moesif_aws_lambda/middleware.py#L136

**Comment by dgilling** [comment]
@amersulieman We released a fix in v1.0.6. Thanks for reporting.
